package user_test

import (
	"errors"
	"strings"
	"testing"
	"time"

	"task-api/internal/domain/user"
)

func TestNewUsername(t *testing.T) {
	t.Run("accepts and trims a valid username", func(t *testing.T) {
		got, err := user.NewUsername("  alice  ")
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}
		if got != user.Username("alice") {
			t.Fatalf("expected trimmed username, got %q", got)
		}
	})

	t.Run("rejects usernames shorter than 3 characters", func(t *testing.T) {
		_, err := user.NewUsername("ab")
		if !errors.Is(err, user.ErrInvalidUsername) {
			t.Fatalf("expected ErrInvalidUsername, got %v", err)
		}
	})

	t.Run("rejects empty username", func(t *testing.T) {
		_, err := user.NewUsername("   ")
		if !errors.Is(err, user.ErrInvalidUsername) {
			t.Fatalf("expected ErrInvalidUsername, got %v", err)
		}
	})

	t.Run("rejects usernames longer than 255 characters", func(t *testing.T) {
		_, err := user.NewUsername(strings.Repeat("a", 256))
		if !errors.Is(err, user.ErrInvalidUsername) {
			t.Fatalf("expected ErrInvalidUsername, got %v", err)
		}
	})
}

func TestValidatePassword(t *testing.T) {
	tests := []struct {
		name     string
		password string
		isValid  bool
	}{
		{"valid minimum length", "password", true},
		{"valid 72 characters (bcrypt limit)", strings.Repeat("a", 72), true},
		{"too short", strings.Repeat("a", 7), false},
		{"too long (bcrypt limit)", strings.Repeat("a", 73), false},
		{"empty", "", false},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			err := user.ValidatePassword(tt.password)
			if tt.isValid && err != nil {
				t.Fatalf("expected valid password, got %v", err)
			}
			if !tt.isValid && !errors.Is(err, user.ErrInvalidPassword) {
				t.Fatalf("expected ErrInvalidPassword, got %v", err)
			}
		})
	}
}

func TestNewUser(t *testing.T) {
	username, _ := user.NewUsername("alice")
	before := time.Now()

	u := user.NewUser(username, "hashed-password")

	if u.ID == "" {
		t.Fatal("expected aggregate id to be generated by the domain")
	}
	if u.Username != username || u.PasswordHash != "hashed-password" {
		t.Fatalf("unexpected fields: %+v", u)
	}
	if u.CreatedAt.Before(before) || u.UpdatedAt.Before(before) {
		t.Fatal("expected timestamps to be set by the domain")
	}
}
