package task_test

import (
	"errors"
	"strings"
	"testing"
	"time"

	"task-api/internal/domain/task"
)

func TestNewTask(t *testing.T) {
	t.Run("new task starts in pending with generated identity", func(t *testing.T) {
		before := time.Now()

		tsk, err := task.NewTask("Write report", "Quarterly report", "user-1", "project-1")
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}

		if tsk.ID == "" {
			t.Fatal("expected aggregate id to be generated by the domain")
		}
		if tsk.Status != task.StatusPending {
			t.Fatalf("expected status %q, got %q", task.StatusPending, tsk.Status)
		}
		if tsk.Title != "Write report" || tsk.Description != "Quarterly report" || tsk.AssigneeID != "user-1" {
			t.Fatalf("unexpected fields: %+v", tsk)
		}
		if tsk.ProjectID != "project-1" {
			t.Fatalf("expected project project-1, got %q", tsk.ProjectID)
		}
		if tsk.CreatedAt.Before(before) {
			t.Fatal("expected created_at to be set by the domain")
		}
		if tsk.UpdatedAt.Before(before) {
			t.Fatal("expected updated_at to be set by the domain")
		}
	})

	t.Run("trims surrounding whitespace from title", func(t *testing.T) {
		tsk, err := task.NewTask("  Write report  ", "", "user-1", "project-1")
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}
		if tsk.Title != "Write report" {
			t.Fatalf("expected trimmed title, got %q", tsk.Title)
		}
	})

	t.Run("rejects empty title", func(t *testing.T) {
		for _, title := range []string{"", "   "} {
			_, err := task.NewTask(title, "", "user-1", "project-1")
			if !errors.Is(err, task.ErrInvalidTitle) {
				t.Fatalf("expected ErrInvalidTitle for %q, got %v", title, err)
			}
		}
	})

	t.Run("rejects title longer than 255 characters", func(t *testing.T) {
		_, err := task.NewTask(strings.Repeat("a", 256), "", "user-1", "project-1")
		if !errors.Is(err, task.ErrInvalidTitle) {
			t.Fatalf("expected ErrInvalidTitle, got %v", err)
		}
	})

	t.Run("rejects empty assignee", func(t *testing.T) {
		_, err := task.NewTask("Write report", "", "", "project-1")
		if !errors.Is(err, task.ErrInvalidAssignee) {
			t.Fatalf("expected ErrInvalidAssignee, got %v", err)
		}
	})

	t.Run("rejects empty project", func(t *testing.T) {
		_, err := task.NewTask("Write report", "", "user-1", "")
		if !errors.Is(err, task.ErrInvalidProject) {
			t.Fatalf("expected ErrInvalidProject, got %v", err)
		}
	})
}

func TestTaskEnsureOwnedBy(t *testing.T) {
	tsk, _ := task.NewTask("Write report", "", "user-1", "project-1")

	if err := tsk.EnsureOwnedBy("user-1"); err != nil {
		t.Fatalf("expected owner to pass, got %v", err)
	}

	if err := tsk.EnsureOwnedBy("user-2"); !errors.Is(err, task.ErrForbidden) {
		t.Fatalf("expected ErrForbidden for non-owner, got %v", err)
	}
}

func TestTaskChangeDetails(t *testing.T) {
	newTitle := "New title"
	newDesc := "New description"
	completed, _ := task.NewTaskStatus("completed")

	t.Run("applies all changes", func(t *testing.T) {
		tsk, _ := task.NewTask("Old title", "Old description", "user-1", "project-1")

		if err := tsk.ChangeDetails(&newTitle, &newDesc, &completed); err != nil {
			t.Fatalf("unexpected error: %v", err)
		}

		if tsk.Title != newTitle || tsk.Description != newDesc {
			t.Fatalf("expected fields to be updated, got %+v", tsk)
		}
		if tsk.Status != task.StatusCompleted {
			t.Fatalf("expected status completed, got %q", tsk.Status)
		}
	})

	t.Run("nil means unchanged", func(t *testing.T) {
		tsk, _ := task.NewTask("Old title", "Old description", "user-1", "project-1")

		if err := tsk.ChangeDetails(nil, nil, nil); err != nil {
			t.Fatalf("unexpected error: %v", err)
		}

		if tsk.Title != "Old title" || tsk.Description != "Old description" || tsk.Status != task.StatusPending {
			t.Fatalf("expected fields unchanged, got %+v", tsk)
		}
	})

	t.Run("rejects blank replacement title and keeps old value", func(t *testing.T) {
		tsk, _ := task.NewTask("Old title", "", "user-1", "project-1")
		blank := "   "

		if err := tsk.ChangeDetails(&blank, nil, nil); !errors.Is(err, task.ErrInvalidTitle) {
			t.Fatalf("expected ErrInvalidTitle, got %v", err)
		}
		if tsk.Title != "Old title" {
			t.Fatalf("expected title unchanged, got %q", tsk.Title)
		}
	})
}

func TestTaskAssignTo(t *testing.T) {
	t.Run("reassigns and produces an audit log", func(t *testing.T) {
		tsk, _ := task.NewTask("Write report", "", "user-1", "project-1")
		taskID := tsk.ID

		logEntry, err := tsk.AssignTo("user-2", "user-1")
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}

		if tsk.AssigneeID != "user-2" {
			t.Fatalf("expected assignee user-2, got %q", tsk.AssigneeID)
		}
		if logEntry.TaskID != taskID {
			t.Fatalf("expected log task_id %q, got %q", taskID, logEntry.TaskID)
		}
		if logEntry.Action != "assigned" {
			t.Fatalf("expected action %q, got %q", "assigned", logEntry.Action)
		}
		if logEntry.OldValue != "user-1" || logEntry.NewValue != "user-2" {
			t.Fatalf("unexpected log values: %+v", logEntry)
		}
		if logEntry.ChangedBy != "user-1" {
			t.Fatalf("expected changed_by user-1, got %q", logEntry.ChangedBy)
		}
		if logEntry.ID == "" || logEntry.CreatedAt.IsZero() {
			t.Fatal("expected log identity and timestamp to be set")
		}
	})

	t.Run("any caller may reassign; authorization is not the aggregate's concern", func(t *testing.T) {
		tsk, _ := task.NewTask("Write report", "", "user-1", "project-1")

		logEntry, err := tsk.AssignTo("user-3", "user-2")
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}
		if tsk.AssigneeID != "user-3" {
			t.Fatalf("expected assignee user-3, got %q", tsk.AssigneeID)
		}
		if logEntry.ChangedBy != "user-2" {
			t.Fatalf("expected changed_by user-2, got %q", logEntry.ChangedBy)
		}
	})

	t.Run("rejects empty new assignee", func(t *testing.T) {
		tsk, _ := task.NewTask("Write report", "", "user-1", "project-1")

		_, err := tsk.AssignTo("", "user-1")
		if !errors.Is(err, task.ErrInvalidAssignee) {
			t.Fatalf("expected ErrInvalidAssignee, got %v", err)
		}
	})
}
